### ISSUE TITLE
emoji whose name include underscore cannot show

### ISSUE THREAD

**Issue by LewieL** [gitbucket/gitbucket-emoji-plugin#2]
Such as `heavy_check_mark`, `baby_bottle` and so on. The emoji cannot show in issue with underscore(s) in its name. It just show as origin text.

**Comment by nbkhope** [comment]
I've been experiencing that for a while and now that you mentioned it, it's just the ones with underscore indeed. The emojis don't appear after writing my pull requests in GitBucket. It would be nice to have emojis again! 👍

**Comment by takezoe** [comment]
Fixed in markedj 1.0.10. It will be adopted in GitBucket 4.11.

**Comment by takezoe** [comment]
This problem will be fixed by upgrading GitBucket to 4.11. It will be released the end of this month.

**Comment by nbkhope** [comment]
ありがとうございます！

**Comment by LewieL** [comment]
Thanks a lot :)
