### ISSUE TITLE
Where can I see a page with all the emoji available? 

### ISSUE THREAD

**Issue by nbkhope** [gitbucket/gitbucket-emoji-plugin#4]
It would be nice to be able to see all the emoji available in a single page or document, without having to search through the image files one by one to see what they look like. 👀 

There's this [cheatsheet page](https://www.webpagefx.com/tools/emoji-cheat-sheet/) that shows all the emoji available for sites like GitHub and Bitbucket. 😃  Does Gitbucket support the exact same emoji names? ❓

**Comment by takezoe** [comment]
Sorry for my slow reply. I added a link to the cheatsheet to README.md.
