### ISSUE TITLE
Do not show emoji in GitBucket 4.31.2

### ISSUE THREAD

**Issue by kama-meshi** [gitbucket/gitbucket-emoji-plugin#7]
Emoji will be show as alter image in GitBucket 4.31.2. 
Though emoji in completion list will be shown.

This is rendered html.

```
<p><img alt=":persevere:" class="emoji"> </p>
```

plugin: 4.5.1
GitBucket : 4.31.2

![preview](https://user-images.githubusercontent.com/2654235/57902785-dd584f80-78a5-11e9-8f44-ab48a50c68c2.png)
![completion-list](https://user-images.githubusercontent.com/2654235/57902786-df221300-78a5-11e9-8eca-897831ff0600.png)

**Comment by takezoe** [comment]
Thanks for your reporting. Let me take a look.

**Comment by takezoe** [comment]
Hmm... I tested gitbucket-emoji-plugin 4.5.1 on GitBucket 4.31.2 and it worked fine.

<img width="352" alt="Screen Shot 2019-05-18 at 11 51 26" src="https://user-images.githubusercontent.com/1094760/57963708-579ad980-7963-11e9-9e18-e9436fd94708.png">

**Comment by kama-meshi** [comment]
Thank you for your testing,  @takezoe.
Let me check again, then clean install if not worked.

**Comment by kama-meshi** [comment]
Hmm... i tried to clean install but not worked.
Is there something wrong in my environment?

- OS: centos 7
- JRE: openjdk-1.8.0
- WARs: from GitHub Release page

There is my Dockerfile for test.
[gitbucket-emoji-issue-7.zip](https://github.com/gitbucket/gitbucket-emoji-plugin/files/3221596/gitbucket-emoji-issue-7.zip)

```
$ docker build --force-rm=true -t gitbucket-test .
$ docker run --rm -p 8080:8080 gitbucket-test
```

**Comment by takezoe** [comment]
Sorry, it's reproduced in my environment. It seems to be caused by a security fix of markdej which is a markdown parser library used in GitBucket. I need to look deeply to identify the root cause.

**Comment by takezoe** [comment]
Fixed. Try gitbucket-emoji-plugin 4.5.2.

**Comment by kama-meshi** [comment]
Awesome!
It worked. Thanks a lot.
